import Head from 'next/head'
import Image from 'next/image'
import React,{useState, useEffect} from 'react'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import Navbar from '../components/Navbar'
import { useRouter } from 'next/router';

export default function AddKeyNote() {
  const [title, setTitle] = useState('');
  const [content, setContent] = useState('');
  const [videoUrl, setVideoUrl] = useState('');
  const [subject, setSubject] = useState('');
  const [image, setImage] = useState('');
  const [allQuizzes, setQuizzes] = useState([]);
  const [quizzId, setQuizzId] = useState('');

  const router = useRouter();

  useEffect(() => {
    axios.get('http://localhost:5000/get_all_quizzes').then((response) => {
        setQuizzes(response.data.quizzes);
    });
  }, []);

  const AddKey = (e) => {

    const formData = new FormData();
    formData.append('title', title);
    formData.append('content', content);
    formData.append('videoUrl', videoUrl);
    formData.append('key_image', image);
    formData.append('subject', subject);
    formData.append('quizzId', quizzId);

    const config = {
      headers: { 
        'content-type': 'multipart/form-data' }
     }
    
    axios.post('http://localhost:5000/add_keynote', formData, config).then((res) => {
      if(res.data.msg == "Keynote added successfully"){
        router.push('/');
      }
    }).catch((err) => {
      console.log(err);
    })

    e.preventDefault();
}
 
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      

      <main className={styles.main}>
      <h1 className={styles.h1}>Add Keynote</h1>
      <div className={styles.formcontainer}>
      <hr/>
      <div className={styles.container}>
        <label htmlFor="title"><strong>Title</strong></label>
        <input onChange={(e) => (setTitle(e.target.value))} className={styles.input} type="text" placeholder="Enter keynote title" name="title" required/>
        
        <label htmlFor="content"><strong>Content</strong></label>
        <textarea onChange={(e) => (setContent(e.target.value))} className={styles.input} rows="4" cols="50" placeholder="Enter content" name="content" required></textarea>

        <label htmlFor="subject"><strong>Subject</strong></label>
        <input onChange={(e) => (setSubject(e.target.value))} className={styles.input} type="text" placeholder="Enter subject" name="subject" required/>

        <label htmlFor="videoUrl"><strong>Video Url</strong></label>
        <input onChange={(e) => (setVideoUrl(e.target.value))} className={styles.input} type="text" placeholder="Enter video url" name="videoUrl" required/>
        
        <label htmlFor="quiz"><strong>Select Quiz</strong></label>
        <select onChange={(e) => (setQuizzId(e.target.value))} className={styles.select_quiz_input}>
        {allQuizzes.map((quizz, index) => (
            <option value={quizz._id} key={index}>{quizz.title}</option>
        ))}
        </select>
        <br/>
        <br/>
        <label className={styles.uploadImageButton} htmlFor="image">Image</label>

        <input onChange={(e) => setImage(e.target.files[0])} className={styles.fileInput} type="file" id="image"/>

      </div>
      <button onClick={(e) => AddKey(e)} className={styles.button} type="submit">Add</button>
      
      
      </div>
        
      </main>


    </div>
  )
}