import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import React,{useState, useEffect} from 'react'
import { useRouter } from 'next/router'
import axios from 'axios'
import Navbar from '../components/Navbar'
import 'bootstrap/dist/css/bootstrap.css'

export default function Home() {
  const [Quizzes, setQuizzes] = useState([]);
  const router = useRouter();
  useEffect(() => {
    getQuizzes();
  },[]);

  const quizzImagePath = "http://localhost:5000/uploads/quiz_images/";

  const getQuizzes = () => {
    axios.get('http://localhost:5000/get_all_quizzes').then((response) => {
      setQuizzes(response.data.quizzes);
  });
  }

  const quizzDetails = (quizzId) => {
    router.push({
        pathname: '/quizzdetails',
        query: { quizzId: quizzId }
    });
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar/>
      
      <div className='container'>
      <div className='allposts'>

      {Quizzes.map((quizz, index) => {
        return(
          <div onClick={() => quizzDetails(quizz._id)} key={index} className='postCard'>
            <img src={quizzImagePath+quizz.image} alt='Quizz Image'/>
            <div className='post-date'>{quizz.created_at}</div>
            <h3>{quizz.title}</h3>
            <p>{quizz.question}</p>
          </div>
        )
      })}
      


      </div>
    </div>
    </div>
  )
}
