import Head from 'next/head'
import Image from 'next/image'
import React,{useState, useEffect} from 'react'
import axios from 'axios'
import Navbar from '../components/Navbar'
import 'bootstrap/dist/css/bootstrap.min.css';
import { withRouter } from 'next/router';
import $ from 'jquery';
import Popper from 'popper.js';

function KeynoteDetails(props) {
  const [keynote, setKeynote] = useState('');
  const keynoteImagePath = "http://localhost:5000/uploads/keynote_images/";
  useEffect(() => {
    const keynoteId = props.router.query.keynoteId;
    if(keynoteId != null){
      localStorage.setItem('id', keynoteId);
    }

    let id = localStorage.getItem('id');
        axios.get(`http://localhost:5000/get_keynote_by_id?keynoteId=${id}`).then((response) => {
            setKeynote(response.data.keynote);
          
        })
    }, []);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div className='QuizzDetailBox'>
      <div className='quizImage'>
        <Image src={keynoteImagePath+keynote.keynote_image} layout="fill"/>
      </div>
      <div className='QuizzText'>
      <h1 className='subject'>{keynote.title}</h1>
      <h5 className='subject'>{keynote.subject}</h5>
      <h5 className='questionTag'>Content</h5>
      <p className='question'>{keynote.content}</p>
      <h5 className='difficultyTag'>Video Url</h5>
      <a href={keynote.videoUrl} className='answer'>Video Solution</a>
      
      <div>
      </div>
      </div>
      </div>



    </div>
  )
}

export default withRouter(KeynoteDetails);