import Head from 'next/head'
import Image from 'next/image'
import React,{useState, useEffect} from 'react'
import axios from 'axios'
import Navbar from '../components/Navbar'
import { withRouter } from 'next/router';

function Solution(props) {
  const [keynote, setKeynote] = useState('');
  const keynoteImagePath = "http://localhost:5000/uploads/keynote_images/";


  useEffect(() => {
    const quizzId = props.router.query.quizzId;

    if(quizzId != null){
      localStorage.setItem('id', quizzId);
    }

    let id = localStorage.getItem('id');
        axios.get(`http://localhost:5000/get_keynote_by_quizzId?quizzId=${id}`).then((response) => {
            setKeynote(response.data.keynote);
        })
    }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    {keynote != null ?
    <div className='QuizzDetailBox'>
      <div className='quizImage'>
        <Image src={keynoteImagePath+keynote.keynote_image} layout="fill"/>
      </div>
      <div className='QuizzText'>
      <h1 className='subject'>{keynote.title}</h1>
      <h5 className='subject'>{keynote.subject}</h5>
      <h5 className='questionTag'>Content</h5>
      <p className='question'>{keynote.content}</p>
      <h5 className='difficultyTag'>Video Url</h5>
      <a href={keynote.videoUrl} className='answer'>Video Solution</a>
      <div>

      </div>
      </div>
      </div>:
      <p>No key is available</p>}



    </div>
  )
}

export default withRouter(Solution);